### ISSUE TITLE
Automatic creation of anti-tracker extensions settings for websites

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#222]
## Project description

I can use NoScript. Some also can but don't want to toggle noscript settings and troubleshoot and analyse the shit. They are ideal targets for blackmailing them with "allow scripts and trackers or go out of my site".

Currently these users have to allow scripts globally, including all the trackers, exploits, malware and similar shit. This is definitely not OK.

If they have decided to allow oneself to be blackmailed, there is nothing we can do about that.

But we can probably do something else. There are still some sites not blackmailing, but still containing trackers. Can we derive a minimal set of scripts that should be allowed to preserve their usability?

Let's assumme that if there is no visible large UI change the website is working.

1. A hardened Firefox with an ad-blocker is used. Websites disallowing ad-blockers are out of scope. Ads gonna introduce noise in out measurements. Rarely-used shit like webgl, sensors, wasm, webaudio is disabled.
2. a website is opened with all the scripts allowed.
3. website is automatically functionally tested:

search in state graph in breadth-first way (symbolic execution can also be used):
4. page layout is checked aginst db of fingerprints of known GUI states
5. all the elements with events listeners are identified.
6. interpreter, dom, caches, cookies, etc states are snapshoted
7. transitions are done - the tool simulates clicks, text input, etc.
8. the tool monitors API calls and other way instruments the source.
end loop

9. the tool statically analyses all the JavaScript sources and finds there clues that would help it to optimize the search
10. the tool uses genetic algo and/or symbolic execution  to eliminate scrips one by one nkt making any sensible change in GUI relatively to etalon site behavior as a criteria of a working website.
11. minimized set of scripts and the rest of info acquired is saved into the DB
12. cross-site use of the same and/or similar scripts is detected, also source code hostings are analysed, the info is used to classify the scripts into trackers and non-trackers using natural language processing of comments, functions names , readmes and docs, AST should also be mined. After that humans should vet the machine decision.
13. the list of blackmailers is determined.

14. umatrix is modified to be able to load profiles from web or an offline db
15. if a website is a blackmailer the user gets big red prompt
16. otherwise the profile is applied silently

Limitations
------------------
* Cannot detect tracking blended into main website code.

## Relevant Technology

* xen, virtualbox, qemu
* firejail
* selenium
* firefox
* symbolic execution
* natural language processing
* databases
* AST mining
* WbExtensions
* umatrix

### Complexity

- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [x] AI/ML
- [x] Developer Tooling
- [x] Extension/Plugin/Add-On
- [x] Bots
- [x] Security
- [x] Futuristic Tech/Something Unique
